spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/babies}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE:20}
      minimum-idle: ${MIN_POOL_SIZE:5}
  flyway:
    url: ${FLYWAY_URL:jdbc:postgresql://localhost:5432/babies}
    user: ${FLYWAY_USER:postgres}
    password: ${FLYWAY_PASSWORD:postgres}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migrations}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}
logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
    com.zaxxer.hikari: WARN
    org.hibernate: INFO
cloudinary:
  name: ${CLOUDINARY_NAME}
  api:
    key: ${CLOUDINARY_API_KEY}
    secret: ${CLOUDINARY_API_SECRET}
server:
  port: ${SERVER_PORT:8080}