spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${SERVLET_FILE_SIZE:4MB}
      max-request-size: ${SERVLET_REQUEST_SIZE:10MB}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE}
      minimum-idle: ${MIN_POOL_SIZE}
  flyway:
    url: ${FLYWAY_URL}
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migrations}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
    com.zaxxer.hikari: WARN
    org.hibernate: INFO
cloudinary:
  environment: ${CLOUDINARY_ENVIRONMENT}
  name: ${CLOUDINARY_NAME}
  api:
    key: ${CLOUDINARY_API_KEY}
    secret: ${CLOUDINARY_API_SECRET}
server:
  port: ${SERVER_PORT:8080}